indent_style = "Block"
hard_tabs = true
reorder_imports = true
comment_width = 60
hex_literal_case = "Upper"
match_block_trailing_comma = true
max_width = 110
fn_call_width = 110
wrap_comments = true
