[package]
name = "externsion_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
externsion = { path = "../externsion" }
log = "0.4.17"
